### ISSUE TITLE
Column ctid on foreign table

### ISSUE THREAD

**Issue by thongpvn** [pgspider/sqlite_fdw#14]
I can SELECT ctid from a foreign table.
<pre><code class="SQL">
EXPLAIN (VERBOSE, COSTS OFF)
SELECT ctid, * FROM ft1 t1 LIMIT 1;
                                          QUERY PLAN                                          
----------------------------------------------------------------------------------------------
 Limit
   Output: ctid, c1, c2, c3, c4, c5, c6, c7, c8
   ->  Foreign Scan on public.ft1 t1
         Output: ctid, c1, c2, c3, c4, c5, c6, c7, c8
         SQLite query: SELECT "C 1", "c2", "c3", "c4", "c5", "c6", "c7", "c8" FROM main."T 1"
(5 rows)

SELECT ctid, * FROM ft1 t1 LIMIT 1;
      ctid      | c1 | c2 |  c3   |              c4              |            c5            | c6 |     c7     | c8  
----------------+----+----+-------+------------------------------+--------------------------+----+------------+-----
 (4294967295,0) |  1 |  1 | 00001 | Fri Jan 02 00:00:00 1970 PST | Fri Jan 02 00:00:00 1970 | 1  | 1          | foo
(1 row)
</code></pre>

But I can not SELECT with ctid filter.
<pre><code class="SQL">
EXPLAIN (VERBOSE, COSTS OFF)
SELECT * FROM ft1 t1 WHERE t1.ctid = '(4294967295,0)';
                                                         QUERY PLAN                                                         
----------------------------------------------------------------------------------------------------------------------------
 Foreign Scan on public.ft1 t1
   Output: c1, c2, c3, c4, c5, c6, c7, c8
   SQLite query: SELECT "C 1", "c2", "c3", "c4", "c5", "c6", "c7", "c8" FROM main."T 1" WHERE (("ctid" = '(4294967295,0)'))
(3 rows)

SELECT * FROM ft1 t1 WHERE (t1.ctid = '(4294967295,0)');
 c1 | c2 | c3 | c4 | c5 | c6 | c7 | c8 
----+----+----+----+----+----+----+----
(0 rows)
</code></pre>

Could you help me to resolve this issue?

**Comment by mochizk** [comment]
Thanks for the report.
I fixed the issue. Please confirm.
