### ISSUE TITLE
failed to execute remote SQL: rc=8 attempt to write a readonly database

### ISSUE THREAD

**Issue by mdt-kathur** [pgspider/sqlite_fdw#22]
I build sqlite_fdw in docker based on mdllion/postgis image.
then I did the following
in bash,  
> sqlite3 test.db

in sqlite3, 

> create table test(a integer primary key, b test);
> insert into test values (5, 'foo');

in postgresql

> create extension sqlite_fdw;
> create server sqlite_server foreign data wrapper sqlite_fdw options (database '/test.db');
> CREATE FOREIGN TABLE t1(a integer OPTIONS (key 'true'), b text) SERVER sqlite_server OPTIONS (table 'test');

then I tried to write some record into sqlite using:

> insert into t1 values (8, 'bar');

and it results in that error in the title.
I can read table content but failed to write.  anything I'm doing wrong?

**Comment by kanegoon** [comment]
I think this issue is permission of file.  SQLite said,
```
The SQLITE_READONLY result code is returned when an attempt is made to alter some data for which the current database connection does not have write permission.
```
Please see the following URL.
https://www.sqlite.org/rescode.html

After that, please confirm permission of '/test,db' file.
Additionally, I tried your process. My result is below.

in sqlite3,
```
sqlite> create table test(a integer primary key, b test);
sqlite> insert into test values (5, 'foo');
```

in PostgreSQL
```
postgres=# create extension sqlite_fdw;
postgres=# create server sqlite_server foreign data wrapper sqlite_fdw options (database '/test.db');
postgres=# CREATE FOREIGN TABLE t1(a integer OPTIONS (key 'true'), b text) SERVER sqlite_server OPTIONS (table 'test');
CREATE FOREIGN TABLE
postgres=# insert into t1 values (8, 'bar');
INSERT 0 1
postgres=# SELECT * FROM t1;
 a |  b  
---+-----
 5 | foo
 8 | bar
(2 rows)
```

**Comment by mdt-kathur** [comment]
thanks for the reply!
I just find out that this is a problem caused by docker. If you try to insert data into an SQLite table without mount the folder out, it will always result in a permission error.
