### ISSUE TITLE
"sqlite_fdw_version" function to return current extension version

### ISSUE THREAD

**Issue by AmebaBrain** [pgspider/sqlite_fdw#37]
Thank you for the created extension.

I woul ask you to introduce `sqlite_fdw_version` function which will return current extension version. The same approach is done for example for [mysql_fdw](https://github.com/EnterpriseDB/mysql_fdw) extension.

**Comment by hrkuma** [comment]
Thank you for request.

We'd like to support version check function like mysql_fdw in next time.

**Comment by hrkuma** [comment]
I think it would be like followings.
Please let me know if it is not as your expectation.

``` sql
testdb=# create extension sqlite_fdw;
create extension sqlite_fdw;
CREATE EXTENSION
testdb=# \df sqlite*
                               List of functions
 Schema |         Name         | Result data type | Argument data types | Type
--------+----------------------+------------------+---------------------+------
 public | sqlite_fdw_handler   | fdw_handler      |                     | func
 public | sqlite_fdw_validator | void             | text[], oid         | func
 public | sqlite_fdw_version   | integer          |                     | func
(3 rows)

testdb=# select * from public.sqlite_fdw_version();
select * from public.sqlite_fdw_version();
 sqlite_fdw_version
--------------------
              10301
(1 row)
```

**Comment by AmebaBrain** [comment]
Yes, exactly!

**Comment by hrkuma** [comment]
Thank you for confirmation.
I have added sqlite_fdw_version in 2e71a9b79cb4f2cd725dc16a5d6e87ddc7d07883 .
In next release the function will return released version.
