### ISSUE TITLE
When trying to import entire schema error of type does not exist for specific table

### ISSUE THREAD

**Issue by marielcherkassky** [pgspider/sqlite_fdw#4]
Hi,
In my sqlite database I have a table that one of its column is of type datetime. datetime isnt supported in postgresql therefore when I try to import the entire public schema from sqlite to postgres schema I get the next error : 

import foreign schema public from server sqlite_server into sqlite_foreign_schema
ERROR:  type "datetime" does not exist
LINE 9: "Date" datetime
               ^
QUERY:  CREATE FOREIGN TABLE sqlite_foreign_schema."mytable" (
"ID" bigint OPTIONS (key 'true'),
**"Date" datetime**
) SERVER sqlite_server
OPTIONS (table 'mytable'');
CONTEXT:  importing foreign table "mytable"

So, in that case I should manualy do it for each table ?

**Comment by mochizk** [comment]
> So, in that case I should manualy do it for each table ?
Yes.
Instead, If you can change datetime to timestamp in SQLite, you can use IMPORT FOREIGN SCHEMA.

**Comment by mochizk** [comment]
I committed fix. datetime can be used now.
