### ISSUE TITLE
SQL error during prepare: no such table main.t1_sqlite

### ISSUE THREAD

**Issue by judell** [pgspider/sqlite_fdw#48]
Hi there,

I think I've successfully built the extension, and can do all the steps in the README, but in the end I get the above error when trying `select * from t1` or `select * from public.t1`

What's going on with `main`?

Thanks for doing this project!

**Comment by t-kataym** [comment]
Thank you for your question.

Could you confirm there is 't1_sqlite' table on SQLite?

If not exists, you can create it by SQLite CLI as follows.

1. Open database by SQLite CLI
```sh
$ sqlite3 /tmp/test.db
```

2. Create 't1_sqlite'
```sql
CREATE TABLE t1_sqlite (a integer, b text);
```

3. Exit the CLI
```sql
.q
```

> What's going on with main?

"main" means a database name which you are connecting .
On SQLite, you can connect to multiple databases by using ATTACH DATABASE command.
The 1st opened database(=test.db) can be specified by 'main'.
Please refer https://sqlite.org/lang_attach.html

**Comment by judell** [comment]
Thanks, I was trying to use postgres to create and populate the foreign table. As my interest here was only in reading sqlite data in postgres, not writing, I wound up doing this.

## shell

```
$ sqlite3 /tmp/test.db
> create table t1_sqlite(a int, b text);
> insert into t1_sqlite(a, b) values (1, "one");
```

## psql


```
db# CREATE SERVER sqlite_server FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/tmp/test.db');
CREATE SERVER

db# \d
              List of relations
 Schema |   Name    |     Type      |  Owner   
--------+-----------+---------------+----------
 public | t1_sqlite | foreign table | postgres 

db# select * from t1_sqlite;
 a |  b  
---+-----
 1 | one
```
