### ISSUE TITLE
Flushing data not performed when closing server

### ISSUE THREAD

**Issue by de-sgen** [pgspider/sqlite_fdw#64]
Hello,
we are currently using sqlite_fdw version 2.3.0 and we noticed that, when inserting data in a foreign table, data is not automatically flushed to the disk when the server associated with the table (the one created with 'FOREIGN DATA WRAPPER sqlite_fdw') is dropped. We would need a mechanism to force the writing as we need to move data in a different location. 
Please could you help us understanding how to solve this problem?

Thanks a lot.

Best regards,
Francesco De Angelis

**Comment by mkgrgis** [comment]
@de-sgen , look like this behaviour can be introduced with a new `FOREIGN SERVER` option. In SQLite v3 C API there is [a function we discussed](https://www.sqlite.org/c3ref/db_cacheflush.html). Additional point of view can be near [temporary files ](https://www.sqlite.org/tempfiles.html).
Also see FDW function without flushing https://github.com/pgspider/sqlite_fdw/blob/9fd31f43b08ca64006b86d0de316222c213d0081/connection.c#L244

**Comment by t-kataym** [comment]
@mkgrgis Please let me confirm your scenario.

>  when inserting data in a foreign table, data is not automatically flushed to the disk when the server associated with the table

Did you COMMIT the transaction after inserting data?

**Comment by t-kataym** [comment]
I'm sorry, The previous comment is for @de-sgen

**Comment by mkgrgis** [comment]
Generally warning message can be usefully if there is opened transaction during disconnect. Also if there was unsuccessfully commit during disconnecting.

**Comment by de-sgen** [comment]
Hello @mkgrgis, @t-kataym,
thanks for your messages.
Yes the problem is that, within a transaction and before it ends, we need to ensure that data is written and relocated to a final destination, otherwise we must rollback (among other things, to prevent some race conditions). This means that such steps must occur before the commit.
In my tests I have added a new method to explicitly close the connection (calling "sqlite_finalize_list_stmt" and "sqlite3_close" like in connection.c:sqlite_disconnect_cached_connections). The file is correctly closed but it is empty, even though the foreign table contains some records. 
I have checked other parts of the code: given that "sqlite3_step" is invoked by sqlite_fdw.c:sqlite_execute_insert, I guess that ExecForeignInsert is triggered only upon a commit (but I didn't have time neither to activate and check logs, nor to check the PostgreSQL documentation yet). Am I correct?

Thanks again.

**Comment by t-kataym** [comment]
@de-sgen 

> Yes the problem is that, within a transaction and before it ends, we need to ensure that data is written and relocated to a final destination, otherwise we must rollback (among other things, to prevent some race conditions). This means that such steps must occur before the commit.

I understood that you want to ensure that data is written before commit.  
Could you tell me why it is necessary? Why such steps must occur before commit?  

If there is an error during COMMIT, you can rollback the transaction.  
I think the current implementation can prevent race conditions even if data is not flushed before commit.

> I thought this behaviour could be enforced by closing the server. Given that this is not the case, in my tests I have added a new method to explicitly close the connection (which calls "sqlite_finalize_list_stmt" and "sqlite3_close" like in connection.c:sqlite_disconnect_cached_connections). The file is correctly closed but it is empty, even though the foreign table contains some records.

The transaction data can be seen from the other connections only after commit.
If you don't commit a transaction and close a connection, the transaction data should be ignored (rollback).

> I have checked other parts of the code: given that "sqlite3_step" is invoked by sqlite_fdw.c:sqlite_execute_insert, I guess that ExecForeignInsert is triggered only upon a commit (but I didn't have time neither to activate and check logs, nor to check the PostgreSQL documentation yet). So probably the conclusion is that flushing before committing is not possible, unless there is a way to tune the the behaviour of ExecForeignInsert. Is that right?

ExecForeignInsert is called during INSERT operation not COMMIT.  
But data can be read by the other connections after COMMIT regardless of data is flushed to disk or not.

**Comment by de-sgen** [comment]
> @de-sgen
>
> > Yes the problem is that, within a transaction and before it ends, we need to ensure that data is written and relocated to a final destination, otherwise we must rollback (among other things, to prevent some race conditions). This means that such steps must occur before the commit.
> 
> I understood that you want to ensure that data is written before commit. Could you tell me why it is necessary? Why such steps must occur before commit?
Because the whole transaction revolves around a stored procedure, which returns a code identifying whether a process composed of several steps terminated successfully or not. One of these steps consists in copying the SQLite DB within a given location (this is needed, in a broader system, to prevent some race conditions due to multiple producers-consumers). So this means that the stored procedures must terminate after flushing and copying the content.

> 
> If there is an error during COMMIT, you can rollback the transaction. I think the current implementation can prevent race conditions even if data is not flushed before commit.
> 
> > I thought this behaviour could be enforced by closing the server. Given that this is not the case, in my tests I have added a new method to explicitly close the connection (which calls "sqlite_finalize_list_stmt" and "sqlite3_close" like in connection.c:sqlite_disconnect_cached_connections). The file is correctly closed but it is empty, even though the foreign table contains some records.
> 
> The transaction data can be seen from the other connections only after commit. If you don't commit a transaction and close a connection, the transaction data should be ignored (rollback).
Yes, but for the SQLite data we need to relax the Isolation constraint.

> 
> > I have checked other parts of the code: given that "sqlite3_step" is invoked by sqlite_fdw.c:sqlite_execute_insert, I guess that ExecForeignInsert is triggered only upon a commit (but I didn't have time neither to activate and check logs, nor to check the PostgreSQL documentation yet). So probably the conclusion is that flushing before committing is not possible, unless there is a way to tune the the behaviour of ExecForeignInsert. Is that right?
> 
> ExecForeignInsert is called during INSERT operation not COMMIT. But data can be read by the other connections after COMMIT regardless of data is flushed to disk or not.
Ok so this is strange then, as the method that I have added closes the file after writing some data into the foreign table, so it should not be empty. I will check the logs to understand what is going on.

Thanks.

**Comment by t-kataym** [comment]
> Ok so this is strange then, as the method that I have added closes the file after writing some data into the foreign table, so it should not be empty. I will check the logs to understand what is going on.

If closing a sqlite connection without commit, SQLite rollbacks transaction automatically , I think.

**Comment by de-sgen** [comment]
Thanks for your kind support, problem solved.
