### ISSUE TITLE
roadmap - PostgreSQL 11 support

### ISSUE THREAD

**Issue by ImreSamu** [pgspider/sqlite_fdw#7]
Thank you for this tool!  :heart:  

* Are there any plans to support [PostgreSQL 11](https://www.postgresql.org/about/news/1894/) ?   
( and supporting  PG12dev -  for testing complex DW flow  in a CI tools? )

**Comment by kanegoon** [comment]
Yes, we have already planned to support PostgreSQL 11. Please give us a little more time.
However we have not planned for PG12dev yet.

**Comment by ImreSamu** [comment]
>Yes, we have already planned to support PostgreSQL 11. Please give us a little more time.

Good news!

**Comment by devrimgunduz** [comment]
Following this issue as the RPM packager.

**Comment by mochizk** [comment]
We committed fix for PostgreSQL 11.
We will release the next version on GitHub soon.

**Comment by mochizk** [comment]
@devrimgunduz 
Thanks for creating rpm package!
