### ISSUE TITLE
Branches normalisation

### ISSUE THREAD

**Issue by mkgrgis** [pgspider/sqlite_fdw#77]
Since I get multi-versional testing system for `sqlite_fdw` in https://github.com/pgspider/sqlite_fdw/pull/67#issuecomment-1565269813 I try to study testing system history, but unfortunately there is no historical branches and branch naming rules in `sqlite_fdw`. Now, in opposite to PostgreSQL (see https://github.com/pgspider/sqlite_fdw/releases) here is no accessable `git` release history. It's normal to have some draft branches such as https://github.com/pgspider/sqlite_fdw/branches but it's not normal not to have historical branches and branch naming rules.

My proposal

1. Use PostgreSQL naming rules for usual development branches from https://git.postgresql.org/gitweb/?p=postgresql.git;a=tags
2. Delete non historical and not actual drafts yet merged https://github.com/pgspider/sqlite_fdw/tree/support_postgres_13b2 and https://github.com/pgspider/sqlite_fdw/branches
3. Rename `master` to `REL_2_4_0` or `REL_2_4_BETA`
4. Use `draft_` lowercase prefix for internal draft branches. For example `draft_support_postgres_13b2`
5. Try to restore historical branches from commits before releases.

This branching rules can be usefully for other pgspider repositories, especially FDWs.

**Comment by t-kataym** [comment]
Thank you for your proposal.

Please let me explain the policy of this project.  
* We don't modify the old version of sqlite_fdw even if a bug is fixed.
It means that we don't backport it, the bug fix is applied to only the latest version (=master branch).
* The next version is not decided. Version number is always increased. Currently v2.3.0, the next version might be v3.0.0, v2.4.0 or v2.3.1.
* You can get the release history by listing up tags "git tag".
* Our development is not opened. When we finish a development, we publish the code on GitHub.

**Comment by mkgrgis** [comment]
Thanks, @t-kataym !

> * We don't modify the old version of sqlite_fdw even if a bug is fixed.
>       It means that we don't backport it, the bug fix is applied to only the latest version (=master branch).

But some projects without backports contain historical branches without changes (de facto read-only) . In case of `sqlite_fdw` there is good `git tag` mechanism with normalized names. Thanks, this is what i need to research about history of this project.

3 outdated branches of this repository allows me to mistake about relationship between branch names and tags. Is [this outdated branches](https://github.com/pgspider/sqlite_fdw/branches) necessary if development is not opened? I think there is reason only for master branch, isn't it?

**Comment by t-kataym** [comment]
@mkgrgis , Thank you for your comment.

> 3 outdated branches of this repository allows me to mistake about relationship between branch names and tags. Is [this outdated branches](https://github.com/pgspider/sqlite_fdw/branches) necessary if development is not opened? I think there is reason only for master branch, isn't it?

I have deleted these branches.

**Comment by mkgrgis** [comment]
Many thanks, @t-kataym ! All git structures around this repository are good and clear!
