### ISSUE TITLE
UUID support

### ISSUE THREAD

**Issue by mkgrgis** [pgspider/sqlite_fdw#81]
Hello, @t-kataym!

After discussion in https://github.com/pgspider/sqlite_fdw/issues/66 and ended PR https://github.com/pgspider/sqlite_fdw/pull/79 without SQL behaviour change I am trying to implement some SQL behaviour from _data type - affinity table_ and draft any tests for this cases.

> * **∅** - no support (runtime error)
> * **V** - transparent transformation
> * **b** - show per-bit form
> * **T** - cast to text in SQLite utf-8 encoding, then to **PostgreSQL text with current encoding of database** and then transparent transformation if applicable
> * **✔** - transparent transformation where PostgreSQL datatype is equal to SQLite affinity
> * **V+** - transparent transformation if appliacable
> * **?** - not described/not tested
> * **-** - transparent transformation is possible for PostgreSQL (always or for some special values), but not implemented in `sqlite_fdw`.
> 
> SQLite `NULL` affinity always can be transparent converted for a nullable column in PostgreSQL.
> 
> | PostgreSQL   | SQLite <br> INT  | SQLite <br> REAL | SQLite <br> BLOB | SQLite <br> TEXT | SQLite <br> TEXT but <br>empty|SQLite<br>nearest<br>affinity|
> |-------------:|:------------:|:------------:|:------------:|:------------:|:------------:|-------------:|
> |         bool |     V     |     ?     |     T     |     -     |     ∅     |   INT|
> |       bit(n) |     V     |     ∅     |     V     |     ?     |     ∅     |   INT|
> |        bytea |     b     |     b     |     ✔     |     -     |     ?     |  BLOB|
> |         date |     V     |     V     |     T     |     V+    |   `NULL`  | ? |
> |       float4 |     V+    |     ✔     |     T     |     -    |   `NULL`  | REAL|
> |       float8 |     V+    |     ✔     |     T     |     -    |   `NULL`  | REAL|
> |         int2 |     ✔     |     ?     |     T     |     -    |   `NULL`  |   INT|
> |         int4 |     ✔     |     ?     |     T     |     -    |   `NULL`  |   INT|
> |         int8 |     ✔     |     ?     |     T     |     -    |   `NULL`  |   INT|
> |         json |     ?     |     ?     |     T     |     V+    |     ?     |  TEXT|
> |         name |     ?     |     ?     |     T     |     V     |   `NULL`  |  TEXT|
> |      numeric |     V     |     V     |     T     |     ∅     |   `NULL`  | REAL|
> |         text |     ?     |     ?     |     T     |     ✔     |     V     |  TEXT|
> |         time |     V     |     V     |     T     |     V+    |   `NULL`  | ? |
> |    timestamp |     V     |     V     |     T     |     V+    |   `NULL`  | ? |
> |timestamp + tz|     V     |     V     |     T     |     V+    |   `NULL`  | ? |
> |        uuid |     ∅     |     ∅     |V+<br>(only<br>16 bytes)|     V+    |   `NULL`  |  TEXT, BLOB|
> |      varchar |     ?     |     ?     |     T     |     ✔     |     V     |  TEXT|
> 

In case of `uuid` PostgreSQL data type I have some problems and need your advice.

1. SQLite recommends both `blob`(16) and `text` data affinity for UUID, see https://sqlite.org/src/file/ext/misc/uuid.c ,
2. For `blob`(16) in`SELECT` there is blob->text->uuid grouping algorithm,
3. For deparsing to blob there is  uppercase and `-` exclude algorithm,
4. For text `uuid` we have https://doxygen.postgresql.org/uuid_8c.html#a4a77eee2ce5614bf3cbb23e74d9434c7 which implements https://www.postgresql.jp/document/15/html/datatype-uuid.html = https://www.postgresql.org/docs/16/datatype-uuid.html Let's note, we have _normalized_ output but _some possible_ inputs . This means in case of deparse PostgreSQL always will give us _normalized_ value like `a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11` but our fdw should also gives in `WHERE` predicate such values as 

> A0EEBC99-9C0B-4EF8-BB6D-6BB9BD380A11
> {a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11}
> a0eebc999c0b4ef8bb6d6bb9bd380a11
> a0ee-bc99-9c0b-4ef8-bb6d-6bb9-bd38-0a11
> {a0eebc99-9c0b4ef8-bb6d6bb9-bd380a11}

*Current `uuid` support* is very limited: no `blob`(16) support at all, only `a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11` form works in deparse cases. I think real equal predicate looks like `replace(replace(replace(lower(SQLite_UUID), '{', ''), '}', ''), '-', '') = replace(PG_UUID, '-', '') OR hex(SQLite_UUID) = upper(replace(PG_UUID, '-', ''));`. Please note this predicate is pushdownable because of [`lower`](https://www.sqlite.org/lang_corefunc.html#lower) under hex ASCII subset is pushdownable. Also in SQlite  there is ISO:SQL [`replace` function](https://www.sqlite.org/lang_corefunc.html#replace) for our subset.

My SQLite tests
```
CREATE TABLE UUID (
    UUID TEXT
);
INSERT INTO UUID (UUID) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11');
INSERT INTO UUID (UUID) VALUES ('A0EEBC99-9C0B-4EF8-BB6D-6BB9BD380A11');
INSERT INTO UUID (UUID) VALUES ('{a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11}');
INSERT INTO UUID (UUID) VALUES ('a0eebc999c0b4ef8bb6d6bb9bd380a11');
INSERT INTO UUID (UUID) VALUES ('a0ee-bc99-9c0b-4ef8-bb6d-6bb9-bd38-0a11');
INSERT INTO UUID (UUID) VALUES ('{a0eebc99-9c0b4ef8-bb6d6bb9-bd380a11}');
INSERT INTO UUID (UUID) VALUES (x'A0EEBC999C0B4EF8BB6D6BB9BD380A11');

select UUID,
       hex(UUID)
  from UUID
 where replace(replace(replace(lower(UUID), '{', ''), '}', ''), '-', '') = replace('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '-', ''
    or hex(UUID) = upper(replace('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '-', ''));
```

Summary
1. In `SELECT` context case based on affinity
2. In `WHERE` the described predicate

Could you give me your opinion, @t-kataym, please ?

**Comment by mkgrgis** [comment]
I have implemented SQLite both text and blob UUID support with some obvious test for our FDW, @t-kataym. Could you give me feedback, please? 

My draft based on https://github.com/pgspider/sqlite_fdw/pull/79 is [here ](https://github.com/mkgrgis/sqlite_fdw/tree/draft_uuid). Unfortunately Famous existed problem with searching of not-normalised by PostgreSQL values was leaved because i have no ideas where to implement `replace(replace(replace(lower(SQLite_UUID), '{', ''), '}', ''), '-', '') = replace(PG_UUID, '-', '') OR hex(SQLite_UUID) = upper(replace(PG_UUID, '-', ''));` comparison.

**Comment by mkgrgis** [comment]
Updated to https://github.com/pgspider/sqlite_fdw/pull/82

**Comment by t-kataym** [comment]
@MinhLA1410 , Could you confirm it?

**Comment by nxhai98** [comment]
Hello @mkgrgis,
I checked this issue and your implement in #82, below are some comment:

> 1. In SELECT context case based on affinity

The implement in [#82](https://tccloud2.toshiba.co.jp/accio/redmine/issues/82) create a function to convert blob(16) UUID to text.
However, PostgreSQL can read blob(16) UUID directly by something like below, no need to create a custom function.
```C
pg_uuid_t  *retval = (pg_uuid_t *) palloc0(sizeof(pg_uuid_t));
memcpy(retval->data, sqlite_blob, UUID_LEN); // sqlite_blob length must be 16
return UUIDPGetDatum(retval);
```
> 2. In WHERE the described predicate

I think the main problem here is different UUID store/comparison in PostgreSQL and SQLite:
SQLite, there is no binary type for UUID, user can store UUID with BLOB or TEXT type:
- BLOB affinity: stores the binary form of the UUID value with 16 bytes, this storage is independent of the UUID format.
- TEXT affinity: stores text presentation of UUID value and no generic format, SQLite will compare this as a normal text value => UUID format will affect the result:
```sql
sqlite> INSERT INTO UUID (UUID) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11');
sqlite> INSERT INTO UUID (UUID) VALUES ('{a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11}');

sqlite> SELECT UUID, UUID = '{a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11}' FROM UUID;
a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11|0
{a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11}|1
```
Postgres:
- Postgres internal store UUID value in `pg_uuid_t` structure (all text presentation of UUID value will convert to this data structure (16 bytes array)) => the comparison is not depending on text presentation:
```sql
select 'A0EEBC99-9C0B-4EF8-BB6D-6BB9BD380A11'::uuid = '{a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11}'::uuid;
 ?column? 
----------
 t
(1 row)
```
Due to different spec, I think it has better if the UUID comparison should be calculated on PostgreSQL to make consistent. (do not push-down UUID constant/function/...)


Could you please share your opinion?

**Comment by mkgrgis** [comment]
Hello @nxhai98 !

> ... However, PostgreSQL can read blob(16) UUID directly by something like below, no need to create a custom function.

Thanks for note. I'll improve my implementation and run all tests again. I am still not sure in searching in PostgreSQL source codes and haven't seen usefully `UUIDPGetDatum`. Direct transfer is important for `SELECT` productivity in case of millions UUIDs. 

> I think the main problem here is different UUID store/comparison in PostgreSQL and SQLite: SQLite, there is no binary type for UUID, user can store UUID with BLOB or TEXT type

Yes. This problem is a part of global problem calls "ISO:SQL behavior of PostgreSQL and non ISO:SQL behavior of SQLite". It's central problem for all of my contribution to this FDW.

> * BLOB affinity: stores the binary form of the UUID value with 16 bytes, this storage is independent of the UUID format.

Yes, this storage is not very readable but is _1 to 1_ with ISO:SQL UUID like in PostgreSQL.

> * TEXT affinity: stores text presentation of UUID value and no generic format...

Yes. "No generic format" means non ISO:SQL behavior.

> Due to different spec, I think it has better if the UUID comparison should be calculated on PostgreSQL to make consistent. (do not push-down UUID constant/function/...)
> Could you please share your opinion?

My opinion is we should not try to implement non-pusdownable functions if we can implement someone with minimal data traffic between SQLite and PostgreSQL. What about SQLite table with 4Gb of UUIDs only and some other columns?

You have wrote "_it has better if the UUID comparison should be calculated on PostgreSQL_". Does it means not _only_ in PostgreSQL but "better if the UUID comparison should be calculated by _ISO:SQL rules_ (also implemented by PostgreSQL)"? What about pushdownable predicate on SQLite side like `substr(u, 1, 8) || '-' || substr(u, 8, 12) || '-' || substr(u, 12, 16) || '-' || substr(u, 16, 20) || '-' || substr(u, 20, 12)`  where `u` is `replace(replace(replace(lower(UUID), '{', ''), '}', ''), '-', '')` ?
How do you think is this a good idea to give a hard work with SQLite text UUIDs to SQLite, not to PostgreSQL? Note: this idea still not implemented in my PR.

**Comment by mkgrgis** [comment]
Hello, @nxhai98 ! My PR fixed to `pg_uuid_t`, thanks to your comment. There was no SQL behaviour change, but faster UUID as BLOB data transfer.

**Comment by nxhai98** [comment]
@mkgrgis , thank for updating, I seen the changed.


> You have wrote "it has better if the UUID comparison should be calculated on PostgreSQL". Does it means not only in PostgreSQL but "better if the UUID comparison should be calculated by ISO:SQL rules (also implemented by PostgreSQL)"? What about pushdownable predicate on SQLite side like substr(u, 1, 8) || '-' || substr(u, 8, 12) || '-' || substr(u, 12, 16) || '-' || substr(u, 16, 20) || '-' || substr(u, 20, 12) where u is replace(replace(replace(lower(UUID), '{', ''), '}', ''), '-', '') ?
How do you think is this a good idea to give a hard work with SQLite text UUIDs to SQLite, not to PostgreSQL? Note: this idea still not implemented in my PR.

I think it too specific for UUID equal comparison, for another operator or support more UUID form, it may more complex.

How do you think about:
- just support UUID in SQLite in BLOB (16) type, the behavior same with Postgres UUID. If UUID specify on foreign table, we assume that SQLite column is in BLOB (16) type, Constant push down should be UUID binary data (BLOB (16)).
- if UUID in SQLite is text affinity => SQLite process it as a normal text value => user should define this column in Postgres as TEXT column, the behavior is the same also, push-down can work normally, no need any specific implementation.

**Comment by mkgrgis** [comment]
> I think it too specific for UUID equal comparison, 

No, this is specific for UUID _text_ comparison. This complex query also allows to sort texts for UUIDs like normal UUIDs.

> ... for another operator or support more UUID form, it may more complex.

This predicate will be more complex only in case full one-time `text` and `BLOB` affinities support for UUIDs. For this case I have more short way, see below.

> How do you think about:
>  * just support UUID in SQLite in BLOB (16) type ...

This means to disallow text affinity for UUIDs. This way look like [oracle_fdw](https://github.com/laurenz/oracle_fdw/), because there is no text UUIDs in Oracle at all, only `RAW(16)` storage and some functions for this data type only. In PostgreSQL and Oracle text UUIDs are exotic and very rare.

[Firebird](https://firebirdsql.org/file/documentation/chunk/en/refdocs/fblangref30/fblangref30-functions-uuid.html) and [MariaDB(MySQL)](https://dev.mysql.com/blog-archive/mysql-8-0-uuid-support/) gives us tiny set of UUID functions like `UUID` (generating function), `UUID_TO_BIN`, `BIN_TO_UUID`, `IS_UUID`. This means text UUIDs is usual in this RDBMS. In SQLite we have no default UUID functions, only extensions. Hence text UUIDs is usual for SQLite usage.

> * if UUID in SQLite is text affinity => SQLite process it as a normal text value => user should define this column in Postgres as TEXT column, the behavior is the same also, push-down can work normally, no need any specific implementation.

This is a good idea only if we have no _mixed_ affinity UUID columns. My idea is we can `select` both affinities, but `insert` or `update` only to value of preferred affinity from `column_type` column option.

Author of [firebird_fdw](https://github.com/ibarwick/firebird_fdw) give me idea to cast UUIDs to `BLOB` affinity due comparison. It seems this idea is adoptable to mixed affinity case in SQLite.  What do you think about UUID deparsing and binding only as blob with such comparison predicate for text values as `unhex(replace(replace(replace(UUID, '}', ''), '{', ''), '-', ''))` ?

For SQLite universal UUID `select` from my tests to this PR there was such cast-to-BLOB query as
```sql
case when typeof(UUID) = 'text'
            then unhex(replace(replace(replace(UUID, '}', ''), '{', ''), '-', ''))
            else UUID
            end as UUID
```
In case of improper characters this function gives `NULL`, in case of improper `BLOB` length our fdw gives error message => no potential problems. Could you please comment this idea, @nxhai98 ?

**Comment by nxhai98** [comment]
@mkgrgis,

> My idea is we can select both affinities, but insert or update only to value of preferred affinity from column_type column option.

I understood this point.

>  It seems this idea is adoptable to mixed affinity case in SQLite. What do you think about UUID deparsing and binding only as blob with such comparison predicate for text values as unhex(replace(replace(replace(UUID, '}', ''), '{', ''), '-', '')) ?

That was good idea. However, `unhex` is not a built-in function of sqlite_fdw, it seems an extension.    
To support like this, we need more condition:
 - In case of `unhex` supported, sqlite_fdw can support the pushdown by that approach.
 - In case of `unhex` unsupported, sqlite_fdw does not pushdown.

I think sqlite_fdw can know `unhex` function is supported on SQLite (for example, executes unhex function actually). But this may not enough to determine `unhex` function is supported by checking only `unhex` function is executable.

BTW, there may more useful extension like `uuid_blob(X)` https://github.com/nalgeon/sqlean/blob/main/docs/uuid.md

If the above is not acceptable,
in case of mixed affinity UUID columns in SQLite, because supporting a pushdown UUID column by sqlite_fdw will be complex to define specification and implementation, it had better not to support the pushdown at all, I think.

**Comment by mkgrgis** [comment]
@nxhai98 thanks for discussing. Look like you can give me some steps to improve my implementation.

> That was good idea. However, `unhex` is not a built-in function of sqlite_fdw, it seems an extension. 

Please refer https://www.sqlite.org/lang_corefunc.html#unhex and [C code](https://github.com/sqlite/sqlite/blob/25033b6b3b888e493a724007080001e45291601b/src/func.c#L1299).  

In my experiments I have found short effective form 
```sql
case when typeof(UUID) = 'text'
            then unhex(UUID, '-{}') -- ignore characters from list in 2nd parameter
            else UUID
            end as UUID
```
In case of PostgreSQL there is equivalent `decode(replace(replace(replace(UUID, '}', ''), '{', ''), '-', ''),'hex')`

Have I wrong understood 

>  `unhex` is not a built-in function of sqlite_fdw ....
> To support like this, we need more condition:
>     * In case of `unhex` supported, sqlite_fdw can support the pushdown by that approach.

I think `unhex` is fully supported in C environment of our FDW. Also I can write in C contextual simplification of the original SQLite SQL function `unhex`. In case of some SQL solution we can use both SQLite or PostgreSQL functions with this transformation.

> I think sqlite_fdw can know `unhex` function is supported on SQLite (for example, executes unhex function actually). But this may not enough to determine `unhex` function is supported by checking only `unhex` function is executable.

I don't understand the second sentence. By documentation `unhex` is available in the main branch of SQLite during many years and applicable to SQLite version `sqlite_fdw` compiled against. Also we can borrow code of this function or implement PostgreSQL SQL equal transformation. This gives us potential liberty of implementation. Isn't it?

> BTW, there may more useful extension like `uuid_blob(X)` https://github.com/nalgeon/sqlean/blob/main/docs/uuid.md

My slow code without fast `pg_uuid_t` + `UUIDPGetDatum` was borrowed from this extension ;-) Thanks to @nalgeon !

> If the above is not acceptable

I think all pointed by you code elements is available in our C environment and acceptable for me as author of this PR.

> ... because supporting a pushdown UUID column by sqlite_fdw will be complex to define specification and implementation, it had better not to support the pushdown at all, I think.

I think I have a chance to implement _full pushdownable mixed affinity UUID support_ with your help. I am not dislike "complex to define specification and implementation" and my tests covers all mixed affinity cases, but represents current  logic with some inconsistency. Could you give me please a key lines of sqlite_fdw to add some functions? I think [read function](https://github.com/mkgrgis/sqlite_fdw/blob/939b6bc79033b74f7c24fd50ac22590e33bed9b0/sqlite_query.c#L366) is normal and we need to modify only `bind` and some from _deparse_ near this [line](https://github.com/mkgrgis/sqlite_fdw/blob/939b6bc79033b74f7c24fd50ac22590e33bed9b0/deparse.c#L2610), isn't it? What will the changes on the way to _full pushdownable mixed affinity UUID support_ you think?

**Comment by mkgrgis** [comment]
Hello, @nxhai98 ! After some researches I have implemented _full pushdownable mixed affinity UUID support_. My ideas was:
- `unhex()` is unavailable in SQLite 3.38. I was wrong, _you was right_;
- adding UUID functions to SQLite during new connection call;
- implement UUID functions in SQLite name context based on borrowing code from https://github.com/nalgeon/sqlean/blob/main/src/uuid/extension.c;
- add deparsing UUID column name with `coalesce` and `uuid_blob` only if new C `bool` value `dml_context` is false.

Could you please check if my tests is complete and if my implementation gives no inconsistent data?

**Comment by nxhai98** [comment]
@mkgrgis Thank for your contributor,

> implement UUID functions in SQLite name context based on borrowing code from https://github.com/nalgeon/sqlean/blob/main/src/uuid/extension.c;
> add deparsing UUID column name with coalesce and uuid_blob only if new C bool value dml_context is false.

This solution looks better than usage of `unhex()`. And this solution is acceptable.
I checked your implement. I think we need create a specific function name instead of `uuid_blob` such as `sqlite_fdw_uuid_blob` to use it only in sqlite_fdw and not conflict with another user.


> Could you please check if my tests is complete and if my implementation gives no inconsistent data?

Your PR has contained other PR code, I cannot review it now. Can you make the independent PR?

**Comment by mkgrgis** [comment]
> a specific function name instead of `uuid_blob` such as `sqlite_fdw_uuid_blob` to use it only in sqlite_fdw and not conflict...

Thanks for note, @nxhai98! I'll fix.

> Your PR has contained other PR code, I cannot review it now.

What are you about? Please describe changes you treat as "other PR code" outside of `README.md`.

For example 

- `sqlite_bind_sql_var`(Oid type, **int pgtypmod**, int attnum, Datum value, sqlite3_stmt * stmt, bool *isnull, **Oid relid** was modified for human readable message about problems with UUID binding (pgtypmod) and options analyze (relid);
- `strcmp_case_independend` was introduced for `column_type` options values like `'Text'` and `'Blob'`;
- `sqlite_deparse_column_ref`(StringInfo buf, int varno, int varattno, PlannerInfo *root, bool qualify_col, **bool dml_context**) was modified for we should deparse UUID column name to unify to UUID BLOB in `SELECT` and `WHERE` but should't for `UPDATE` `DELETE` `INSERT`
- Changes in `sqlite_query.c` represents initial step for explicit [table](https://github.com/pgspider/sqlite_fdw/issues/81#issue-1817810132) "pg data type <-> SQLite affinity" support  from https://github.com/pgspider/sqlite_fdw/pull/79 This was technical PR without tested SQL behavior changes.

**Comment by nxhai98** [comment]
> Function name is fixed now, @nxhai98 , see https://github.com/pgspider/sqlite_fdw/commit/b7ea84166db401c709552142d17198b98259388b

Thank for your fixing.


> Yes. This is changes from previous technical (without SQL behavior changes, this breaks no tests) PR https://github.com/pgspider/sqlite_fdw/pull/79 because without human readable diagnostics and explicit table implementation UUID support can not be full. In my future PRs like https://github.com/pgspider/sqlite_fdw/pull/83 I will row-to-row add tests for the table and implement possible data transformations. You can ensure all normal data transformation cases after switches (SQLite data affinity) in switch (PostgreSQL data type) are without changes, but for most of untested ugly cases there are error message. Is this a problem?

Understood, I'm reviewing PR #82 now. Please wait.

**Comment by mkgrgis** [comment]
Full UUID support implemented, tested and merged with only 1 limitation around of data affinity during `UPDATE`. Thanks to @t-kataym, @MinhLA1410 and @nxhai98 !
