### ISSUE TITLE
Unable to make

### ISSUE THREAD

**Issue by mbwmbw1337** [pgspider/sqlite_fdw#85]
I have postgres 15 and 16 installed.

Seeing this result

```
postgres@dal-edge-3:~/sqlite_fdw$ /usr/bin/gmake USE_PGXS=1
Makefile:41: *** PostgreSQL 11, 12, 13, 14 or 15 is required to compile this extension.  Stop.
postgres@dal-edge-3:~/sqlite_fdw$ make USE_PGXS=1
Makefile:41: *** PostgreSQL 11, 12, 13, 14 or 15 is required to compile this extension.  Stop.
```

**Comment by t-kataym** [comment]
We are in progress to support postgres 16 as #84.

**Comment by mbwmbw1337** [comment]
Shouldn't I still be able to build for Postgres 15 or do I need to uninstall Postgres 16 for that to work?

**Comment by mbwmbw1337** [comment]
Anyone else having this issue where you want to build FDW for a lower version but pg_config is defaulting to the highest version do as follows to prepend the version you wish to compile for
`PATH=/usr/lib/postgresql/**15**/bin:/etc/postgresql/**15**/main:$PATH USE_PGXS=1 make`
`PATH=/usr/lib/postgresql/**15**/bin:/etc/postgresql/**15**/main:$PATH USE_PGXS=1 make install`

**Comment by mbwmbw1337** [comment]
@t-kataym you may want to add this as a workaround as the makefile uses the pg_config to check the version regardless of the /etc/postgresql path. Therefore you need to prepend the bin path of the version you are targeting so the makefile knows you're building for a supported version.

**Comment by mkgrgis** [comment]
> Shouldn't I still be able to build for Postgres 15 or do I need to uninstall Postgres 16 for that to work?

You can build for not one PostgreSQL version if you have PostgreSQL source code trees where `sqlite_fdw` was copied to `contrib` as `sqlite_fdw`.

In case of `USE_PGXS=1` in OS environment default version is the highest, but you can change this behaviour of `make` process in a standard way.

**Comment by mbwmbw1337** [comment]
The instructions though, only say to prepend the postgres home/config path, not the BIN path. 

The solution is to prepend BOTH the bin and home/config path. I will create a pull request to update the docs as the makefile relies on pg_config which sits in the postgres bin path.

For instance this worked:
PATH=/usr/lib/postgresql/**15**/bin:/etc/postgresql/**15**/main:$PATH USE_PGXS=1 make
PATH=/usr/lib/postgresql/**15**/bin:/etc/postgresql/**15**/main:$PATH USE_PGXS=1 make install

**Comment by t-kataym** [comment]
If you installed 2 versions of PostgreSQL (15 and 16), 2 pg_config are also installed.
When you executing pg_config command, if  pg_config for 16 is used, sqlite_fdw will be built for 16. Vice versa.
It depends on the priority of path resolution.

**Comment by t-kataym** [comment]
We have just released new sqlite_fdw supporting PostgreSQL16.0.

**Comment by mbwmbw1337** [comment]
I confirmed this works and tested it. Thank you.
